baseurl = "/"
languageCode = "en-us"
theme = "hugo-theme-hello-friend"
paginate = 10

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "post"
  contentDir = "content"
  # "light" or "dark"
  defaultTheme = "dark"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2
  # Enable to show reading time in minutes for posts
  showReadingTime = true



[languages]
  [languages.en]
    title = "Nafaal's Blog"
    subtitle = ""
    keywords = ""
    copyright = ""
    menuMore = ""
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"

    [languages.en.params.logo]
      logoText = "nafaal.com"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "cv"
        name = "cv"
        url = "/cv"
        weight = 1
      [[languages.en.menu.main]]
        identifier = "writeups"
        name = "writeups"
        url = "/writeups"
        weight = 2
      [[languages.en.menu.main]]
        identifier = "notes"
        name = "notes"
        url = "/notes"
        weight = 3
      [[languages.en.menu.main]]
        identifier = "tools"
        name = "tools"
        url = "/tools"
        weight = 4
